package com.cellmachine.telegram.bot;

public enum ConversationStep {
    CHOOSING_MODE,
    WAITING_FOR_B,
    WAITING_FOR_S,
    CHOOSING_SIZE,
    CHOOSING_STEPS,
    WAITING_FOR_MANUAL_STEPS,
    CHOOSING_DENSITY,
    WAITING_FOR_MANUAL_DENSITY,
    CHOOSING_MASK_ACTION,
    WAITING_FOR_MASK_INPUT,
    WAITING_FOR_SERIALIZED_OPTIONS,
    CHOOSING_WRAP,
    CHOOSING_PALETTE,
    GENERATING
}
